spring:
  application:
    name: gateway

server:
  port: 8020


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  ServerListRefreshInterval: 15000
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
  eager-load:
    enabled: true
  eureka:
    enabled: false

products:
  ribbon:
    listOfServers: localhost:8010

categories:
    ribbon:
      listOfServers: localhost:8011

zuul:
  prefix: /api
  threadPool:
    useSeparateThreadPools: true
  routes:
    products:
      path: /products/**
      serviceId: products
      stripPrefix: false
    categories:
      path: /categories/**
      serviceId: categories
      stripPrefix: false